=== majcn/SchoolStuff/st/Vaje/majcn/vaja4.dtd
<!ELEMENT vpisani (student)>
<!ELEMENT student (ime, ulica?, posta, email+, teza, vpisna)>
<!ELEMENT ime (#PCDATA)> 
<!ELEMENT ulica (#PCDATA)> 
<!ELEMENT posta (#PCDATA)> 
<!ELEMENT email (#PCDATA)> 
<!ELEMENT teza (#PCDATA)> 
<!ELEMENT vpisna (#PCDATA)>

<!ATTLIST teza enota (kg|lb|g) "kg">

=== majcn/SchoolStuff/st/Vaje/oman/Vaja_4/vaja4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vpisani SYSTEM "vaja4.dtd">

<vpisani>
	<student>
		<ime>Janez Novak</ime>
		<ulica>Trzaska 25</ulica>
		<posta>1000</posta>
		<email>janez.novak@student.uni-lj.si</email>
		<email>janez.novak@email.si</email>
		<teza enota="kg">50</teza>
		<vpisna>63123123</vpisna>
	</student>
</vpisani>
